data:
  type: 'cell-tfrecord'
  base_path: './data'
  train_data_pattern: 'cell-train-*.tfrecord'
  eval_data_pattern: 'cell-eval-*.tfrecord'
  vocab_size: 3364

model:
  type: 'cell-merge'
  batch_size: 128
  embed_dim: 128
  hidden_size: 64
  keep_prob: 0.5

train:
  learning_rate: 0.0001
  eval_steps: 100
  train_steps: 10000000
  model_dir: 'logs/cellMergeNLP'

  save_checkpoints_steps: 5000
  loss_hook_n_iter: 1000
  check_hook_n_iter: 100
  min_eval_frequency: 5000
  eval_steps: 5000
  print_verbose: False
  debug: False
