data:
  type: 'tfrecord'
  base_path: '/Users/dhu/Downloads/font-images'
  train_data_pattern: '*.tfrecord'
  eval_data_pattern: 'SimSun.tfrecord'

model:
  type: 'ocr'
  net: 'cnn'
  batch_size: 2

train:
  learning_rate: 0.001

  train_steps: 50000
  model_dir: 'logs/ocr'

  save_checkpoints_steps: 1000
  loss_hook_n_iter: 100
  check_hook_n_iter: 100
  min_eval_frequency: 1000
  eval_steps: 100
  print_verbose: False
  debug: False
