data:
  type: 'text'
  base_path: './data/'
  raw_data_path: './data/paragraphs.txt'
  processed_path: './data/text.npy'
  trainset_size: 1000
  testset_size: 100
  num_classes: 2
  max_seq_length: 40

model:
  type: 'text'
  batch_size: 4
  embed_dim: 200
  keep_prob: 0.5
  rnn_mode: 'BLOCK'
  hidden_size: 200
  num_layers: 2
  num_steps: 20

train:
  learning_rate: 0.001

  train_steps: 8000
  model_dir: 'logs/text'

  save_checkpoints_steps: 100
  loss_hook_n_iter: 100
  check_hook_n_iter: 100
  min_eval_frequency: 100
  eval_steps: 100
  print_verbose: True
  debug: False
