data:
  type: 'text'
  base_path: './data/'
  raw_data_path: './data/paragraphs.txt'
  processed_path: './data/text.npy'
  trainset_size: 10000
  testset_size: 1000
  num_classes: 2
  max_seq_length: 40

model:
  type: 'text'
  batch_size: 96
  embed_dim: 300
  keep_prob: 0.5
  rnn_mode: 'BASIC'
  hidden_size: 300
  num_layers: 2
  num_steps: 35

train:
  learning_rate: 0.001

  train_steps: 50000
  model_dir: 'logs/text'

  save_checkpoints_steps: 1000
  loss_hook_n_iter: 1000
  check_hook_n_iter: 1000
  min_eval_frequency: 1000
  eval_steps: 100
  print_verbose: True
  debug: False
